Repository autumn-radiata/radiata-backend, pull requests merged in 2024-10, with the labels that each got.

#8 [#7] fix(dtabase): 데이터베이스 모듈의 datasource url 수정
  database/src/main/resources/application-database-dev.yml
  database/src/main/resources/application-database.yml
  docker-compose-dev.yml
Labels: 🐞 Bug

#12 feat(test): jacoco 테스트 커버리지 도구 추가
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  lombok.config
Labels: ✅ Test

#10 feat(coupon): 쿠폰 Entity 및 인터페이스, 발급 테스트 코드 추가
  common/src/main/java/radiata/common/domain/coupon/dto/condition/CouponSearchCondition.java
  common/src/main/java/radiata/common/domain/coupon/dto/request/CouponCreateRequestDto.java
  common/src/main/java/radiata/common/domain/coupon/dto/request/CouponUpdateRequestDto.java
  common/src/main/java/radiata/common/domain/coupon/dto/response/CouponResponseDto.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  database/src/main/java/radiata/database/configuration/JpaConfiguration.java
  database/src/main/java/radiata/database/model/BaseEntity.java
  service/coupon/coupon-core/build.gradle
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/CouponCoreApplication.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/model/Coupon.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/model/CouponIssue.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/model/constant/CouponSaleType.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/model/constant/CouponStatus.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/model/constant/CouponType.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/model/vo/CouponDiscountRate.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/repository/CouponRepository.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/infrastructure/repository/CouponJpaRepository.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/service/interfaces/CouponCreateService.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/service/interfaces/CouponDeleteService.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/service/interfaces/CouponReadService.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/service/interfaces/CouponService.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/service/interfaces/CouponUpdateService.java
  service/coupon/coupon-core/src/test/java/radiata/service/coupon/core/domain/model/CouponTest.java
Labels: ✨ Feature, ✅ Test

#13 [#4] feat(user) : 유저 서버 엔티티,리포 추가
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  database/src/main/resources/application-database-dev.yml
  service/user/user-api/src/main/resources/application.properties
  service/user/user-api/src/main/resources/application.yml
  service/user/user-core/build.gradle
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/entity/PointHistory.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/entity/User.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/vo/Address.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/vo/Point.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/vo/PointType.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/vo/UserRole.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/repository/PointHistoryRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/repository/UserRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/infrastructure/PointHistoryJpaRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/infrastructure/UserJpaRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/usercore/UserCoreApplication.java
  service/user/user-core/src/test/java/radiata/service/user/core/domain/entity/UserTest.java
  service/user/user-core/src/test/java/radiata/service/user/core/domain/vo/PointTest.java
  service/user/user-core/src/test/java/radiata/service/user/core/usercore/UserCoreApplicationTests.java
Labels: ✨ Feature, ✅ Test

#14 [#6] feat(order): 주문 서비스 엔티티 및 리포지토리 추가 & 테스트 코드 작성
  common/src/main/java/radiata/common/domain/order/dto/request/OrderCreateRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderItemCreateRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/response/OrderItemResponseDto.java
  common/src/main/java/radiata/common/domain/order/dto/response/OrderResponseDto.java
  service/order/order-core/build.gradle
  service/order/order-core/src/main/java/radiata/service/order/core/Main.java
  service/order/order-core/src/main/java/radiata/service/order/core/OrderCoreConfiguration.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/constant/OrderStatus.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/Order.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/OrderItem.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/repository/OrderRepository.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderIdCreator.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderReader.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderSaver.java
  service/order/order-core/src/main/java/radiata/service/order/core/infrastructure/repository/OrderJpaRepository.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/mapper/OrderMapper.java
  service/order/order-core/src/main/resources/application-test.yml
  service/order/order-core/src/test/java/radiata/service/order/core/domain/model/entity/OrderTest.java
  service/order/order-core/src/test/java/radiata/service/order/core/domain/service/OrderServiceTest.java
Labels: ✨ Feature, ✅ Test

#19 [#15] feat: 토스페이먼츠 결제 검증 API 추가
  common/src/main/java/radiata/common/domain/payment/dto/request/TossPaymentCreateRequestDto.java
  common/src/main/java/radiata/common/domain/payment/dto/response/TossPaymentCreateResponseDto.java
  common/src/main/java/radiata/common/message/SuccessMessage.java
  service/payment/payment-api/build.gradle
  service/payment/payment-api/src/main/java/radiata/service/payment/api/Main.java
  service/payment/payment-api/src/main/java/radiata/service/payment/api/PaymentApplication.java
  service/payment/payment-api/src/main/java/radiata/service/payment/api/presentation/PaymentController.java
  service/payment/payment-api/src/main/resources/application-dev.yml
  service/payment/payment-api/src/main/resources/application.yml
  service/payment/payment-core/src/main/java/radiata/service/payment/core/ComponentScanConfiguration.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/config/RestTemplateConfig.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/entity/Payment.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/repository/PaymentRepository.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/implementation/PaymentRequester.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/implementation/PaymentSaver.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/service/TossPaymentService.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/service/request/TossPaymentConfirmRequestDto.java
Labels: ✨ Feature

#25 [#18] Feat/order api: 주문 API & 서비스 테스트 코드
  service/order/order-api/build.gradle
  service/order/order-api/src/main/java/radiata/service/order/api/Main.java
  service/order/order-api/src/main/java/radiata/service/order/api/OrderApiApplication.java
  service/order/order-api/src/main/java/radiata/service/order/api/presentation/OrderController.java
  service/order/order-api/src/main/resources/application.yml
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/Order.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderService.java
Labels: ✨ Feature, ✅ Test

#21 [#16]Feat/유저 서비스 로직 API, TEST 코드 추가
  .gitignore
  common/src/main/java/radiata/common/domain/user/dto/request/UserCreateRequestDto.java
  common/src/main/java/radiata/common/domain/user/dto/request/UserModifyRequestDto.java
  common/src/main/java/radiata/common/domain/user/dto/response/PointHistoryGetResponseDto.java
  common/src/main/java/radiata/common/domain/user/dto/response/UserGetInfoResponseDto.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  database/src/main/resources/application-database-dev.yml
  service/user/user-api/Auth.http
  service/user/user-api/build.gradle
  service/user/user-api/src/main/java/radiata/service/user/api/UserApiApplication.java
  service/user/user-api/src/main/java/radiata/service/user/api/presentation/AuthController.java
  service/user/user-api/src/main/java/radiata/service/user/api/presentation/UserController.java
  service/user/user-api/src/main/resources/application.yml
  service/user/user-api/src/test/java/radiata/service/user/api/userapi/UserApiApplicationTests.java
  service/user/user-core/build.gradle
  service/user/user-core/src/main/java/radiata/service/user/core/ComponentScanConfiguration.java
  service/user/user-core/src/main/java/radiata/service/user/core/config/SecurityConfig.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/constant/PointType.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/constant/UserRole.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/entity/PointHistory.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/entity/User.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/vo/Address.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/vo/Point.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/vo/PointType.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/repository/PointHistoryRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/repository/UserRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/implement/PointHandler.java
  service/user/user-core/src/main/java/radiata/service/user/core/infrastructure/PointHistoryJpaRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/infrastructure/UserJpaRepository.java
  service/user/user-core/src/main/java/radiata/service/user/core/service/AuthService.java
  service/user/user-core/src/main/java/radiata/service/user/core/service/Mapper/UserMapper.java
  service/user/user-core/src/main/java/radiata/service/user/core/service/UserCommandService.java
  service/user/user-core/src/main/java/radiata/service/user/core/service/UserQueryService.java
  service/user/user-core/src/test/java/radiata/service/user/core/domain/entity/UserTest.java
  service/user/user-core/src/test/java/radiata/service/user/core/domain/vo/PointTest.java
Labels: ✨ Feature, ✅ Test

#33 [#28] feat(payment): 결제 확인 API 응답 수정, 테스트 코드 작성
  common/src/main/java/radiata/common/domain/payment/dto/response/TossPaymentCreateResponseDto.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/service/TossPaymentService.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/implementation/PaymentRequesterTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/implementation/PaymentSaverTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/service/TossPaymentServiceTest.java
Labels: ✨ Feature, ✅ Test

#34 [#26] Feature(Order): 주문 Controller & Service 기본 구현(테스트 코드 포함)
  common/src/main/java/radiata/common/domain/order/dto/request/OrderItemCreateRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderPaymentRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/response/OrderItemResponseDto.java
  common/src/main/java/radiata/common/domain/order/dto/response/OrderResponseDto.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  common/src/main/java/radiata/common/message/SuccessMessage.java
  service/order/order-api/build.gradle
  service/order/order-api/src/main/java/radiata/service/order/api/presentation/OrderController.java
  service/order/order-core/build.gradle
  service/order/order-core/src/main/java/radiata/service/order/core/config/JpaConfig.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/constant/OrderStatus.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/Order.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/OrderItem.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderIdCreator.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderReader.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderValidator.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderItemService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/mapper/OrderItemMapper.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/mapper/OrderMapper.java
  service/order/order-core/src/test/java/radiata/service/order/core/domain/model/entity/OrderTest.java
  service/order/order-core/src/test/java/radiata/service/order/core/domain/service/OrderServiceTest.java
Labels: ✨ Feature, ✅ Test

#30 [#27] TimeSale Create, Read API 추가
  common/src/main/java/radiata/common/domain/timesale/dto/condition/TimeSaleSearchCondition.java
  common/src/main/java/radiata/common/domain/timesale/dto/request/TimeSaleCreateRequestDto.java
  common/src/main/java/radiata/common/domain/timesale/dto/response/TimeSaleResponseDto.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  common/src/main/java/radiata/common/message/SuccessMessage.java
  service/timesale/timesale-api/build.gradle
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/Main.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/TimeSaleApiApplication.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/controller/TimeSaleController.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/service/TimeSaleApiService.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/service/TimeSaleApiServiceImpl.java
  service/timesale/timesale-api/src/main/resources/application-timesale-api.yml
  service/timesale/timesale-core/build.gradle
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/Main.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/TimeSaleCoreConfiguration.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/domain/BaseEntity.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/domain/TimeSale.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/domain/TimeSaleProduct.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/domain/repository/TimeSaleQueryRepository.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/domain/repository/TimeSaleRepository.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/TimeSaleCreateRequestDtoValidatorImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/TimeSaleIdCreatorImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/TimeSaleReaderImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/TimeSaleSaverImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/interfaces/TimeSaleCreateRequestDtoValidator.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/interfaces/TimeSaleIdCreator.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/interfaces/TimeSaleReader.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/interfaces/TimeSaleSaver.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/infrastructure/repository/TImeSaleQueryRepositoryImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/infrastructure/repository/TimeSaleJpaRepository.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/TimeSaleServiceImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/interfaces/TimeSaleCreateService.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/interfaces/TimeSaleReadService.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/interfaces/TimeSaleService.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/mapper/TimeSaleMapper.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/mapper/TimeSaleMapperImpl.java
  service/timesale/timesale-core/src/test/java/radiata/service/timesale/core/domain/TimeSaleProductTest.java
Labels: ✨ Feature, ✅ Test

#38 [#37] feat(database): 멀티 datasource 추가
  database/build.gradle
  database/src/main/java/radiata/database/DatabaseModuleConfig.java
  database/src/main/java/radiata/database/configuration/DataSourceConfig.java
  database/src/main/java/radiata/database/property/BatchDataSourceProperty.java
  database/src/main/java/radiata/database/property/MainDataSourceProperty.java
  database/src/main/java/radiata/database/property/RedisProperty.java
  database/src/main/resources/application-database-dev.yml
  docker-compose-dev.yml
  service/payment/payment-api/src/main/java/radiata/service/payment/api/PaymentApplication.java
Labels: ✨ Feature

#45 [#42] deploy: CD 배포 적용
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  docker-compose-deploy.yml
  service/brand/brand-api/build.gradle
  service/coupon/coupon-api/build.gradle
  service/coupon/coupon-api/src/main/resources/application-api.yml
  service/eureka/eureka-core/build.gradle
  service/gateway/gateway-core/build.gradle
  service/order/order-api/build.gradle
  service/payment/payment-api/build.gradle
  service/timesale/timesale-api/build.gradle
  service/user/user-api/build.gradle
Labels: 🌏 Deploy

#46 [#42] fix(deploy): 디렉토리 수정
  Dockerfile
Labels: 🌏 Deploy

#52 [#42] fix(deploy): eureka, gateway 경로 수정
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#53 [#42] fix(deploy): 빌드와 도커 업로드를 하나의 잡으로 통합
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#54 [#42] fix(deploy): 병렬 작업을 직렬 작업으로 변경
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#55 [#42] fix(deploy): DOCKER_HUB_USERNAME 오타 수정
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#56 [#42] fix(deploy): 도커 이미지로 빌드 추가
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#57 [#42] fix(deploy): 권한 추가
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#58 [#42] fix(deploy): appleboy/ssh-action 버전을 v1.0.3 으로 변경
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#60 [#42] feat(deploy): 코드 최적화
  .github/workflows/cd.yml
  docker-compose-deploy.yml
Labels: 🌏 Deploy

#47 [#35] [Feat] 주문 서비스 -OpenFeign & Kafka 추가
  common/src/main/java/radiata/common/domain/order/dto/request/OrderCreateRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderItemCreateRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/response/OrderItemResponseDto.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  service/order/order-api/build.gradle
  service/order/order-api/src/main/java/radiata/service/order/api/OrderApplication.java
  service/order/order-api/src/main/resources/application.yml
  service/order/order-core/build.gradle
  service/order/order-core/src/main/java/radiata/service/order/core/OrderCoreConfiguration.java
  service/order/order-core/src/main/java/radiata/service/order/core/config/KafkaConfig.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/Order.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/OrderItem.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderItemService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/CouponIssueClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/PaymentClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/ProductClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/TimeSaleProductClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/UserClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/mapper/OrderItemMapper.java
  service/order/order-core/src/test/java/radiata/service/order/core/domain/model/entity/OrderTest.java
  service/order/order-core/src/test/java/radiata/service/order/core/domain/service/OrderServiceTest.java
Labels: ✨ Feature

#65 [#61] feat: 스웨거, 유레카 추가
  build.gradle
  service/brand/brand-api/build.gradle
  service/brand/brand-api/src/main/java/radiata/service/brand/api/config/SwaggerConfig.java
  service/coupon/coupon-api/build.gradle
  service/coupon/coupon-api/src/main/java/radiata/service/coupon/api/config/SwaggerConfig.java
  service/coupon/coupon-api/src/main/resources/application-api.yml
  service/gateway/gateway-core/build.gradle
  service/gateway/gateway-core/src/main/resources/application.yml
  service/order/order-api/build.gradle
  service/order/order-api/src/main/java/radiata/service/order/api/config/SwaggerConfig.java
  service/order/order-api/src/main/resources/application.yml
  service/payment/payment-api/build.gradle
  service/payment/payment-api/src/main/java/radiata/service/payment/api/config/SwaggerConfig.java
  service/payment/payment-api/src/main/resources/application.yml
  service/timesale/timesale-api/build.gradle
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/config/SwaggerConfig.java
  service/timesale/timesale-api/src/main/resources/application-timesale-api.yml
  service/user/user-api/build.gradle
  service/user/user-api/src/main/java/radiata/service/user/api/config/SwaggerConfig.java
Labels: 📝 Docs, ✨ Feature

#73 [#hotfix] fix(deploy): 배포 버전으로 수정
  database/src/main/resources/application-database-dev.yml
  service/brand/brand-api/src/main/resources/application.yml
  service/coupon/coupon-api/src/main/resources/application-api.yml
  service/eureka/eureka-core/src/main/resources/application.yml
  service/gateway/gateway-core/src/main/resources/application.yml
  service/order/order-api/src/main/resources/application.yml
  service/payment/payment-api/src/main/resources/application.yml
  service/timesale/timesale-api/src/main/resources/application-timesale-api.yml
Labels: 🌏 Deploy

#74 [#hotfix] fix(deploy): 변경 못 적용한 부분 적용
  docker-compose-deploy.yml
  service/user/user-api/src/main/resources/application.yml
Labels: 🐞 Bug, 🌏 Deploy

#75 [#hotfix] fix(deploy): 유레카에서 호스트네임 삭제
  service/brand/brand-api/src/main/resources/application.yml
  service/coupon/coupon-api/src/main/resources/application-api.yml
  service/eureka/eureka-core/src/main/resources/application.yml
  service/order/order-api/src/main/resources/application.yml
  service/payment/payment-api/src/main/resources/application.yml
  service/timesale/timesale-api/src/main/resources/application-timesale-api.yml
  service/user/user-api/src/main/resources/application.yml
Labels: 🌏 Deploy

#76 [#hotfix] fix(deploy): 게이트웨이에 각 도메인 라우팅 추가
  database/src/main/resources/application-database.yml
  service/coupon/coupon-api/src/main/java/radiata/service/coupon/api/CouponApiApplication.java
  service/coupon/coupon-api/src/main/resources/application-api.yml
  service/gateway/gateway-core/src/main/java/radiata/service/gateway/core/config/GatewayConfig.java
  service/payment/payment-api/src/main/java/radiata/service/payment/api/PaymentApplication.java
Labels: 🐞 Bug, 🌏 Deploy

#77 [#hotfix] fix(deploy): common 모듈 스캔 지정
  service/brand/brand-api/src/main/java/radiata/service/brand/api/BrandApplication.java
  service/order/order-api/src/main/java/radiata/service/order/api/OrderApplication.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/TimeSaleApiApplication.java
  service/user/user-api/src/main/java/radiata/service/user/api/UserApiApplication.java
Labels: 🐞 Bug, 🌏 Deploy

#78 [#hotfix] fix(deploy): common 모듈 스캔 지정
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/TimeSaleApiApplication.java
  service/user/user-api/src/main/java/radiata/service/user/api/UserApiApplication.java
Labels: 🐞 Bug, 🌏 Deploy

#84 [#82] feat(payment): 간편결제 유저 도메인 API 추가
  common/src/main/java/radiata/common/domain/payment/dto/request/PayUserAddMoneyRequestDto.java
  common/src/main/java/radiata/common/domain/payment/dto/request/PayUserCreateRequestDto.java
  common/src/main/java/radiata/common/domain/payment/dto/request/PayUserSubtractMoneyRequestDto.java
  common/src/main/java/radiata/common/domain/payment/dto/response/PayUserResponseDto.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  service/payment/payment-api/http/payuser-api.http
  service/payment/payment-api/src/main/java/radiata/service/payment/api/presentation/PayUserController.java
  service/payment/payment-api/src/main/java/radiata/service/payment/api/presentation/PaymentController.java
  service/payment/payment-core/build.gradle
  service/payment/payment-core/src/main/java/radiata/service/payment/core/config/PasswordEncoderConfig.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/entity/FirmBankingRequestHistory.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/entity/MoneyChangeHistory.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/entity/PayAccount.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/entity/PayUser.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/repository/PayUserRepository.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/implementation/PayUserReader.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/implementation/PayUserSaver.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/implementation/PayUserValidator.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/infrastructure/PayUserJpaRepository.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/service/PayUserService.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/service/mapper/PayUserMapper.java
Labels: ✨ Feature

#89 [#87] feat(deploy): Graceful shutdown 적용
  .github/workflows/cd.yml
  docker-compose-deploy.yml
  service/brand/brand-api/src/main/resources/application.yml
  service/coupon/coupon-api/src/main/resources/application-api.yml
  service/eureka/eureka-core/src/main/resources/application.yml
  service/gateway/gateway-core/src/main/resources/application.yml
  service/order/order-api/src/main/resources/application.yml
  service/payment/payment-api/src/main/resources/application.yml
  service/timesale/timesale-api/src/main/resources/application-timesale-api.yml
  service/user/user-api/src/main/resources/application.yml
Labels: ✨ Feature, 🌏 Deploy

#91 [#86] feat(payment): 간편결제 결제 API 추가
  common/src/main/java/radiata/common/domain/payment/constant/Bank.java
  common/src/main/java/radiata/common/domain/payment/constant/FirmBankingRequestStatus.java
  common/src/main/java/radiata/common/domain/payment/constant/PaymentStatus.java
  common/src/main/java/radiata/common/domain/payment/constant/PaymentType.java
  common/src/main/java/radiata/common/domain/payment/dto/request/EasyPayCreateRequestDto.java
  common/src/main/java/radiata/common/domain/payment/dto/request/TossPaymentCreateRequestDto.java
  common/src/main/java/radiata/common/domain/payment/dto/response/PaymentCreateResponseDto.java
  service/gateway/gateway-core/src/main/java/radiata/service/gateway/core/config/GatewayConfig.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/Order.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/PaymentClient.java
  service/payment/payment-api/http/easypay-scenario.http
  service/payment/payment-api/src/main/java/radiata/service/payment/api/presentation/PaymentController.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/entity/FirmBankingRequestHistory.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/entity/Payment.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/domain/model/vo/Account.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/implementation/PaymentRequester.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/implementation/PaymentSaver.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/service/EasyPayPaymentService.java
  service/payment/payment-core/src/main/java/radiata/service/payment/core/service/TossPaymentService.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/domain/model/entity/FirmBankingRequestHistoryTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/domain/model/entity/PayAccountTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/domain/model/entity/PaymentTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/domain/model/vo/AccountTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/domain/model/vo/BankTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/implementation/PaymentRequesterTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/implementation/PaymentSaverTest.java
  service/payment/payment-core/src/test/java/radiata/service/payment/core/service/TossPaymentServiceTest.java
Labels: ✨ Feature

#85 [#83] Feat/order 주문 등록 - 쿠폰 서비스 Feign연동 추가
  service/order/order-api/http/order-api.http
  service/order/order-api/src/main/resources/application.yml
  service/order/order-core/build.gradle
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/OrderItem.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderItemService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/CouponIssueClient.java
  service/order/order-core/src/test/java/radiata/service/order/core/domain/model/entity/OrderTest.java
Labels: ✨ Feature

#95 [#80] Feat/order 주문 결제 승인 요청 - Feign 연동 추가 & 서비스 코드 분할 작업 & Kafka 설정 추가
  common/src/main/java/radiata/common/domain/order/dto/request/AddPointRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/AddStockRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderCreateRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderEasyPaymentRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderItemCreateRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderPaymentRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/OrderTossPaymentRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/response/CouponInfoDto.java
  common/src/main/java/radiata/common/domain/order/dto/response/StockInfoDto.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  service/order/order-api/src/main/java/radiata/service/order/api/presentation/OrderController.java
  service/order/order-api/src/main/resources/application.yml
  service/order/order-core/src/main/java/radiata/service/order/core/config/KafkaConfig.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/Order.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderCreateService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderItemService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderReadService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderRequestService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderUpdateService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/ProcessService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/RollbackService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/PaymentClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/ProductClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/TimeSaleProductClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/UserClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/context/OrderRollbackContext.java
Labels: ✨ Feature, 🔨 Refactor

#99 [#98] Feat(brand,user) 보상 트랜잭션 추가
  service/brand/brand-api/src/main/resources/application.yml
  service/brand/brand-core/build.gradle
  service/brand/brand-core/src/main/java/radiata/service/brand/core/config/KafkaConfig.java
  service/brand/brand-core/src/main/java/radiata/service/brand/core/implement/IdCreator.java
  service/brand/brand-core/src/main/java/radiata/service/brand/core/service/EventSerializer.java
  service/brand/brand-core/src/main/java/radiata/service/brand/core/service/ProductCommandService.java
  service/user/user-core/build.gradle
  service/user/user-core/src/main/java/radiata/service/user/core/config/KafkaConfig.java
  service/user/user-core/src/main/java/radiata/service/user/core/domain/model/entity/User.java
  service/user/user-core/src/main/java/radiata/service/user/core/service/EventSerializer.java
  service/user/user-core/src/main/java/radiata/service/user/core/service/UserCommandService.java
Labels: ✨ Feature

#101 [#90] Feat/order 주문 자동 취소 스케줄러 구현
  common/src/main/java/radiata/common/domain/order/dto/response/OrderResponseDto.java
  service/order/order-api/src/main/resources/application.yml
  service/order/order-core/build.gradle
  service/order/order-core/src/main/java/radiata/service/order/core/OrderCoreConfiguration.java
  service/order/order-core/src/main/java/radiata/service/order/core/config/KafkaConfig.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/BaseEntity.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/Order.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/OrderItem.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/repository/OrderQueryRepository.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/repository/OrderRepository.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderReader.java
  service/order/order-core/src/main/java/radiata/service/order/core/implemetation/OrderRemover.java
  service/order/order-core/src/main/java/radiata/service/order/core/infrastructure/repository/OrderQueryRepositoryImpl.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/EventSerializer.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderReadService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/ProcessService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/RollbackService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/mapper/OrderMapper.java
Labels: ✨ Feature

#103 [#102] feat(timeSaleProduct): 가장 높은 상품 가져오기 List 로 전환
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  service/coupon/coupon-consumer/src/main/java/radiata/service/coupon/consumer/listener/CouponIssueListener.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/model/Coupon.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/domain/repository/CouponRepository.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/implementation/CouponReaderImpl.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/implementation/interfaces/CouponReader.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/infrastructure/repository/CouponJpaRepository.java
  service/coupon/coupon-core/src/main/java/radiata/service/coupon/core/service/CouponIssueServiceImplV1.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/controller/TimeSaleProductController.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/service/TimeSaleProductApiService.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/service/TimeSaleProductApiServiceImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/domain/repository/TimeSaleQueryRepository.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/TimeSaleReaderImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/implementation/interfaces/TimeSaleReader.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/infrastructure/repository/TimeSaleQueryRepositoryImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/TimeSaleProductServiceImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/interfaces/TimeSaleProductReadService.java
Labels: 🔨 Refactor

#104 [#24] feat(payment): 가상스레드로 정산 배치 처리 추가
  build.gradle
  database/src/main/java/radiata/database/configuration/DataSourceConfig.java
  database/src/main/resources/application-database-dev.yml
  lombok.config
  service/payment/payment-api/build.gradle
  service/payment/payment-api/src/main/java/radiata/service/payment/api/batch/ApprovedPayment.java
  service/payment/payment-api/src/main/java/radiata/service/payment/api/batch/Launcher.java
  service/payment/payment-api/src/main/java/radiata/service/payment/api/batch/SettleJob.java
  service/payment/payment-api/src/main/java/radiata/service/payment/api/config/BatchConfig.java
Labels: ✨ Feature

#106 [none] feat(responseTimeChecker): 리스폰스 타임 체커 추가
  common/build.gradle
  common/src/main/java/radiata/common/aop/ResponseTimeCheck.java
  common/src/main/java/radiata/common/aop/ResponseTimeCheckAspect.java
Labels: ✨ Feature

#109 [#108] feat(timeSaleProduct): 타임세일상품 재고 감소 로직 리팩토링 : 낱개 -> 다량
  common/src/main/java/radiata/common/domain/timesale/dto/request/TimeSaleProductSaleRequestDto.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/controller/TimeSaleProductController.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/service/TimeSaleProductApiService.java
  service/timesale/timesale-api/src/main/java/radiata/service/timeslae/api/service/TimeSaleProductApiServiceImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/domain/TimeSaleProduct.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/TimeSaleProductServiceImpl.java
  service/timesale/timesale-core/src/main/java/radiata/service/timesale/core/service/interfaces/TimeSaleProductUpdateService.java
  service/timesale/timesale-core/src/test/java/radiata/service/timesale/core/domain/TimeSaleProductTest.java
Labels: 🔨 Refactor, ✅ Test

#111 fix(couponIssue): yml kafka 서버 추가
  service/timesale/timesale-api/src/main/resources/application-timesale-api.yml
Labels: 🐞 Bug

#114 [#96] Feat&Refactor/order 주문 등록 - 타임세일 할인 계산 로직 추가 & 카프카 설정 및 객체 수정
  common/src/main/java/radiata/common/domain/order/dto/request/AddPointRequestDto.java
  common/src/main/java/radiata/common/domain/order/dto/request/AddStockRequestDto.java
  common/src/main/java/radiata/common/domain/payment/dto/request/PaymentCancelRequestDto.java
  service/order/order-core/src/main/java/radiata/service/order/core/domain/model/entity/OrderItem.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/EventSerializer.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderItemService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/OrderReadService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/ProcessService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/RollbackService.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/client/TimeSaleProductClient.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/context/OrderRollbackContext.java
Labels: ✨ Feature, 🔨 Refactor

#118 [] refactor(order): 주문 - 각 서비스 별 롤백 요청 타입 수정 완료
  service/order/order-core/src/main/java/radiata/service/order/core/service/EventSerializer.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/RollbackService.java
Labels: 🔨 Refactor

#117 [#116] feat(deploy): 서브 도메인으로 DB 도메인 변경
  build.gradle
  database/src/main/resources/application-database-dev.yml
  service/brand/brand-api/src/main/resources/application.yml
  service/coupon/coupon-api/src/main/resources/application-api.yml
  service/coupon/coupon-consumer/src/main/resources/application-consumer.yml
  service/order/order-api/src/main/resources/application.yml
  service/payment/payment-api/src/main/java/radiata/service/payment/api/listener/PaymentRollbackListener.java
  service/payment/payment-api/src/main/resources/application.yml
  service/timesale/timesale-api/src/main/resources/application-timesale-api.yml
  service/timesale/timesale-consumer/src/main/resources/application-consumer.yml
  service/user/user-api/src/main/resources/application.yml
  settings.gradle
  support/logging/build.gradle
  support/logging/src/main/java/radiata/support/logging/Main.java
  support/monitoring/build.gradle
  support/monitoring/src/main/java/radiata/support/monitoring/Main.java
Labels: ✨ Feature, 🌏 Deploy

#119 [] feat(order): 주문 - FeignException HttpStatus, 메시지, 코드 파싱
  common/src/main/java/radiata/common/exception/BusinessException.java
  common/src/main/java/radiata/common/message/ExceptionMessage.java
  service/order/order-core/src/main/java/radiata/service/order/core/service/ProcessService.java
Labels: ✨ Feature

#121 [#120] feat(gateway): 게이트웨이에서 다른 서비스의 스웨거를 볼 수 있도록 수정
  database/src/main/resources/application-database.yml
  service/gateway/gateway-core/src/main/resources/application.yml
Labels: ✨ Feature
